# Generated by Django 4.1.7 on 2023-03-30 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='star',
            field=models.IntegerField(default=5),
        ),
    ]
